# Generated by Django 5.0.8 on 2024-09-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductPic',
            field=models.ImageField(default='null.jpg', null=True, upload_to='frontend/src/products'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Avatar',
            field=models.ImageField(default='null.jpg', null=True, upload_to='frontend/src/users'),
        ),
    ]
