# Generated by Django 5.0.8 on 2024-09-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0006_alter_product_productpic_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Category', models.ImageField(blank=True, default='null.jpg', null=True, upload_to='static/users')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(blank=True, related_name='category', to='Ecomm.category'),
        ),
    ]
