# Generated by Django 5.0.8 on 2024-09-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0007_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category',
            field=models.ImageField(blank=True, default='null.jpg', null=True, upload_to='static/category'),
        ),
    ]
