# Generated by Django 5.0.8 on 2024-09-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0008_alter_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='Title',
        ),
    ]
